SOURCES = \
././__init__.py \
././definitions/__init__.py \
././definitions/db_defs.py \
././definitions/midvatten_defs.py \
././midvatten_plugin.py \
././midvsettingsdialog.py \
././tools/__init__.py \
././tools/base_importer.py \
././tools/calculate_level.py \
././tools/calculate_statistics.py \
././tools/column_values_from_selected_features.py \
././tools/create_db.py \
././tools/create_db_dialogs.py \
././tools/custom_drillreport.py \
././tools/customplot/__init__.py \
././tools/customplot/_customplot.py \
././tools/customplot/plot_object.py \
././tools/drillreport.py \
././tools/drillreport_models.py \
././tools/export_data.py \
././tools/export_engine.py \
././tools/export_fieldlogger.py \
././tools/export_spatialite.py \
././tools/export_worker.py \
././tools/import_data_to_db.py \
././tools/import_fieldlogger.py \
././tools/import_general_csv_gui.py \
././tools/import_interlab4.py \
././tools/import_logger/__init__.py \
././tools/import_logger/importer.py \
././tools/import_logger/parsers.py \
././tools/loadlayers.py \
././tools/loggereditor.py \
././tools/loggereditor_refseries.py \
././tools/loggereditor_resolve_dupes.py \
././tools/midvsettings.py \
././tools/obsid_assignment_dialog.py \
././tools/piper.py \
././tools/prepareforqgis2threejs.py \
././tools/sectionplot/__init__.py \
././tools/sectionplot/_sectionplot.py \
././tools/sectionplot/_ui_fill.py \
././tools/sectionplot/_utils.py \
././tools/sectionplot/data.py \
././tools/sectionplot/figure.py \
././tools/sectionplot/legend.py \
././tools/sectionplot/painters.py \
././tools/sectionplot/settings.py \
././tools/sectionplot/ui_types.py \
././tools/strat_symbology.py \
././tools/stratigraphy.py \
././tools/trend_math.py \
././tools/tsplot.py \
././tools/utils/__init__.py \
././tools/utils/common_utils.py \
././tools/utils/date_utils.py \
././tools/utils/db_utils/__init__.py \
././tools/utils/db_utils/backends/__init__.py \
././tools/utils/db_utils/backends/base.py \
././tools/utils/db_utils/backends/postgresql.py \
././tools/utils/db_utils/backends/sqlite.py \
././tools/utils/db_utils/connection.py \
././tools/utils/db_utils/dialect.py \
././tools/utils/db_utils/errors.py \
././tools/utils/db_utils/execution.py \
././tools/utils/db_utils/helpers.py \
././tools/utils/db_utils/schema.py \
././tools/utils/db_utils/settings.py \
././tools/utils/db_utils/sqlfile.py \
././tools/utils/dialog_utils.py \
././tools/utils/exceptions.py \
././tools/utils/file_utils.py \
././tools/utils/gui_utils.py \
././tools/utils/layer_build.py \
././tools/utils/layer_specs.py \
././tools/utils/layer_utils.py \
././tools/utils/legend_picker.py \
././tools/utils/matplotlib_replacements.py \
././tools/utils/message_utils.py \
././tools/utils/midvatten_utils.py \
././tools/utils/mpl_compat.py \
././tools/utils/sampledem.py \
././tools/utils/string_utils.py \
././tools/utils/util_translate.py \
././tools/w_flow_calc_aveflow.py \
././tools/wqualreport.py \
././tools/wqualreport_compact.py \
././tools/wqualreport_core.py \
././tools/xyplot.py \
././ui/__init__.py \

FORMS = \
./ui/calc_aveflow_dialog.ui \
./ui/calc_lvl_dialog.ui \
./ui/calculate_statistics_ui.ui \
./ui/calibr_logger_dialog_integrated.ui \
./ui/compact_w_qual_report.ui \
./ui/custom_drillreport.ui \
./ui/customplotdialog.ui \
./ui/export_fieldlogger_ui_dialog.ui \
./ui/fieldlogger_parameter_browser.ui \
./ui/import_fieldlogger.ui \
./ui/import_interlab4.ui \
./ui/midvsettingsdock.ui \
./ui/not_found_gui.ui \
./ui/obs_lines.ui \
./ui/obs_lines_en.ui \
./ui/obs_points.ui \
./ui/obs_points_en.ui \
./ui/secplotdockwidget.ui \
./ui/selected_features.ui \
./ui/simpleplotdialog.ui \
./ui/strat_symbology_dialog.ui \
./ui/stratigraphy.ui \
./ui/stratigraphy_en.ui \
./ui/w_flow.ui \
./ui/w_flow_en.ui \
./ui/w_levels.ui \
./ui/w_levels_en.ui \
./ui/w_lvls_last_geom.ui \
./ui/w_lvls_last_geom_en.ui \

TRANSLATIONS = \
./i18n/midvatten_pt_BR.ts \
./i18n/midvatten_sv_SE.ts \
./i18n/midvatten_en_US.ts
