# AUTO-GENERATED from secplotdockwidget.ui — do not edit manually.
# Regenerate: python tools/sectionplot/generate_ui_types.py
from qgis.PyQt import QtWidgets


class SecPlotUi:
    sec_plot_dock: QtWidgets.QDockWidget
    dock_widget_contents: QtWidgets.QWidget
    scroll_area: QtWidgets.QScrollArea
    scroll_area_widget_contents: QtWidgets.QWidget
    tab_widget: QtWidgets.QTabWidget
    plot_tab: QtWidgets.QWidget
    widget_plot: QtWidgets.QWidget
    settings_tab: QtWidgets.QWidget
    widget_2: QtWidgets.QWidget
    widget_4: QtWidgets.QWidget
    settingsdock_widget: QtWidgets.QDockWidget
    dock_widget_contents_2: QtWidgets.QWidget
    settingswidget: QtWidgets.QWidget
    push_button: QtWidgets.QPushButton
    line: QtWidgets.QFrame
    wlvl_groupbox: object
    label: QtWidgets.QLabel
    include_views_check_box: QtWidgets.QCheckBox
    wlvltable: QtWidgets.QComboBox
    specific_dates_groupbox: QtWidgets.QGroupBox
    label_3: QtWidgets.QLabel
    datetime: QtWidgets.QTextEdit
    interactive_groupbox: QtWidgets.QGroupBox
    resample_offset: QtWidgets.QLineEdit
    resample_rule: QtWidgets.QLineEdit
    label_9: QtWidgets.QLabel
    resample_how: QtWidgets.QLineEdit
    resample_offset_label: QtWidgets.QLabel
    label_11: QtWidgets.QLabel
    skip_nan: QtWidgets.QCheckBox
    dem_groupbox: object
    dem_list: QtWidgets.QListWidget
    label_13: QtWidgets.QLabel
    dem_sampling_distance: QtWidgets.QDoubleSpinBox
    secplot_apply_graded_dems: QtWidgets.QGroupBox
    label_16: QtWidgets.QLabel
    label_17: QtWidgets.QLabel
    label_15: QtWidgets.QLabel
    secplot_grading_max_opacity: QtWidgets.QDoubleSpinBox
    label_14: QtWidgets.QLabel
    secplot_grading_min_opacity: QtWidgets.QDoubleSpinBox
    secplot_grading_num_layers: QtWidgets.QSpinBox
    secplot_grading_depth: QtWidgets.QDoubleSpinBox
    bar_groupbox: object
    textcol_combo_box: QtWidgets.QComboBox
    labels_check_box: QtWidgets.QCheckBox
    label_2: QtWidgets.QLabel
    drillstop: QtWidgets.QLineEdit
    widget: QtWidgets.QWidget
    plot_stratigraphy: QtWidgets.QRadioButton
    hydrology_radio_button: QtWidgets.QRadioButton
    radio_button: QtWidgets.QRadioButton
    label_6: QtWidgets.QLabel
    label_8: QtWidgets.QLabel
    label_5: QtWidgets.QLabel
    widget_3: QtWidgets.QWidget
    width_of_profile: QtWidgets.QRadioButton
    width_of_plot: QtWidgets.QRadioButton
    barwidthdouble_spin_box: QtWidgets.QDoubleSpinBox
    widget_5: QtWidgets.QWidget
    text_align_center: QtWidgets.QRadioButton
    text_align_edge: QtWidgets.QRadioButton
    label_12: QtWidgets.QLabel
    label_screens: QtWidgets.QLabel
    screens_mode_combo: QtWidgets.QComboBox
    label_screen_width_factor: QtWidgets.QLabel
    screen_width_factor_spin: QtWidgets.QDoubleSpinBox
    label_screen_text: QtWidgets.QLabel
    screen_textcol_combo_box: QtWidgets.QComboBox
    tem_groupbox: object
    tem_alpha_below_doi: QtWidgets.QDoubleSpinBox
    tem_model_name: QtWidgets.QComboBox
    label_22: QtWidgets.QLabel
    tem_rasterized: QtWidgets.QCheckBox
    label_31: QtWidgets.QLabel
    tem_edgecolors: QtWidgets.QLineEdit
    label_23: QtWidgets.QLabel
    label_21: QtWidgets.QLabel
    tem_shading: QtWidgets.QComboBox
    tem_vmin: QtWidgets.QLineEdit
    tem_snap: QtWidgets.QCheckBox
    label_18: QtWidgets.QLabel
    label_19: QtWidgets.QLabel
    label_26: QtWidgets.QLabel
    tem_norm: QtWidgets.QComboBox
    label_10: QtWidgets.QLabel
    tem_vmax: QtWidgets.QLineEdit
    label_25: QtWidgets.QLabel
    tem_colormap: QtWidgets.QComboBox
    label_27: QtWidgets.QLabel
    tem_data_fit: QtWidgets.QCheckBox
    tem_alpha_above_doi: QtWidgets.QDoubleSpinBox
    label_24: QtWidgets.QLabel
    images_groupbox: object
    label_29: QtWidgets.QLabel
    images_alpha: QtWidgets.QLineEdit
    label_30: QtWidgets.QLabel
    images_images: QtWidgets.QListWidget
    images_zorder: QtWidgets.QLineEdit
    label_28: QtWidgets.QLabel
    images_clip: QtWidgets.QCheckBox
    plots_groupbox: object
    create_legend: QtWidgets.QCheckBox
    label_20: QtWidgets.QLabel
    dynamic_plot_size: QtWidgets.QRadioButton
    radio_button_2: QtWidgets.QRadioButton
    label_4: QtWidgets.QLabel
    edit_button: QtWidgets.QPushButton
    label_7: QtWidgets.QLabel
    load_button: QtWidgets.QPushButton
    template_list: QtWidgets.QListWidget
    import_button: QtWidgets.QPushButton
    remove_button: QtWidgets.QPushButton
    save_as_button: QtWidgets.QPushButton
    template_plot_label: QtWidgets.QLabel
